### ISSUE TITLE
how to generate AMI/pitch and  AMI/vad files?

### ISSUE THREAD

**Issue by yan159yan** [ahogg/hogg2019-icassp-jupyter_notebook#1]

**Comment by wly112** [comment]
@ahogg  hi, I'm new on Speaker Change Detection, and I think your approach is very concise and intuitive. When I'm reading your codes, I'm trobuled with generating PITCH and VAD files too. Could you please explain it further? Thanks.

**Comment by ahogg** [comment]
So I used VOICEBOX. To be more specific I used PEFAC to generate the pitch tracks and the VOICEBOX VAD (see links below). They are very easy to use and work out of the box.

If you are interested in pitch I also recommend looking up Mads Græsbøll Christensen's group at Aalborg University. His group produce some of the best pitch estimators available. Jesper Kjær Nielsen from this group has put a few these estimators online including this one:
Code: https://github.com/jkjaer/fastF0Nls
Video: https://youtu.be/F0XgU-9ERp4

VoiceBox: https://github.com/ImperialCollegeLondon/sap-voicebox
PEFAC: https://github.com/ImperialCollegeLondon/sap-voicebox/blob/master/voicebox/v_fxpefac.m
VAD: https://github.com/ImperialCollegeLondon/sap-voicebox/blob/master/voicebox/v_vadsohn.m

Let me know if you need anymore help!
